### ISSUE TITLE
Set the generated path to posts to be plain /:title/

### ISSUE THREAD

**Issue by lakruzz** [kea-dev/kea-dev.github.io#4]
The default in the minima theme is to generate a path to the posts that is quite long: `/category1/.../categoryn/YYYY/MM/DD/Title.html`.

Yikes I don't like that - I want it simply to be something like:

`/lay-out-type/title/` like `posts/title`

**Comment by lakruzz** [comment]
I reference this issue from a few attempts - but [this code](https:://github.com/kea-dev/kea-dev.github.io/blob/4c9b494733136ababa3e905a9e472d4ba47ce80a/docs/_config.yml#L33-L36
)

``` yaml
collections:
  posts:
    output: true
    permalink: /posts/:title/
```

in 273718ff07d49ca9e08f310fe6f0bd3a4733aae6 was the one that nailed it
